In [1]:
from dash import Dash, html, dcc, callback, Output, Input
import dash_bootstrap_components as dbc
import plotly.express as px
import pandas as pd

In [2]:
df = pd.read_csv('dataframes/with_counts/soul_count.csv')

In [20]:
app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

artists = list(df.Artist.unique())

items = [{"label": artist, "value": artist} for artist in artists]

app.layout = html.Div([
    html.H1(children = 'First Dash App', style={'textAlign': 'center'}),
    # dcc.Dropdown(df.Artist.unique(), 'Al Green', id='artist-selection'),
    # dbc.DropdownMenu(label="Artist", id="artist-selection", children=items),
    dbc.Select(id="artist-selection", options=items),
    dcc.Graph(id='graph-content')
])

In [21]:
df.head()

,Unnamed: 0.1,Unnamed: 0,Artist,Song Title,Full Title,Release Date,Year,Month,Day,Pageviews,...,money,violence,drugs,gendered,sadness,joy,yes,no,gender,genre
0,0,0,Al Green,Let’s Stay Together,Let's Stay Together by Al Green,NaN,1971.0,11.0,NaN,279512,...,0,0,0,34,4,3,0,0,male,soul
1,1,1,Al Green,Love and Happiness,Love and Happiness by Al Green,1972-10-23,1972.0,10.0,23.0,74572,...,0,0,0,29,0,0,0,1,male,soul
2,2,2,Al Green,How Can You Mend a Broken Heart?,How Can You Mend a Broken Heart? by Al Green,1972-01-31,1972.0,1.0,31.0,72266,...,0,0,0,26,0,0,0,4,male,soul
3,3,3,Al Green,Tired of Being Alone,Tired of Being Alone by Al Green,NaN,1971.0,NaN,NaN,51103,...,0,0,0,14,0,2,0,5,male,soul
4,4,4,Al Green,Take Me to the River,Take Me to the River by Al Green,1974-10-02,1974.0,10.0,2.0,40948,...,1,1,0,18,0,0,0,12,male,soul

In [22]:
@callback(
    Output('graph-content', 'figure'),
    Input('artist-selection', 'value')
)
def update_graph(selected_artist):
    dff = df[df.Artist == selected_artist]
    fig = px.scatter(dff, x='Year', y='sadness')
    return fig

# if __name__ = '__main__':
#     app.run(debug=True)
app.run()